import axios from "axios";
import * as zlib from "node:zlib";
import * as csv from "csvtojson";
import { createBlogFromText } from "../lib/file.utils";

interface Lego {
  set: any;
  title: string;
  year: string;
  theme: string;
  parts: string;
  image: string;
}

interface SyrupDocument {
  uuid: string;
  schema: string;
  attributes: {
    editable: string;
    edit: string;
    view: string;
    tags: string[];
    collections: string[];
  };
  data: {
    type: string;
    content: any[];
  };
  meta: {
    title: string;
    description: string;
    image: string;
    providerId: string;
  };
  type: string;
  bookmarked: boolean;
}

// Helper Functions
export async function downloadLego(legoJsonName: string) {
  const url = "https://cdn.rebrickable.com/media/downloads/sets.csv.gz";
  const response = await axios.get(url, { responseType: "stream" });
  const gunzip = zlib.createGunzip();
  response.data.pipe(gunzip);

  let buffer = Buffer.alloc(0);
  const file: string = await new Promise((resolve, reject) => {
    gunzip.on("data", (chunk) => {
      buffer = Buffer.concat([buffer, chunk]);
    });

    gunzip.on("end", () => {
      resolve(buffer.toString());
    });

    gunzip.on("error", reject);
  });

  const body = await csv({
    noheader: false,
    headers: ["set", "title", "year", "theme", "parts", "image"],
  }).fromString(file);

  const json = await createBlogFromText(
    "data",
    legoJsonName,
    JSON.stringify(body),
    "application/json",
  );

  return { body, json };
}

export async function getLegos(): Promise<Lego[]> {
  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);
  const epoch = today.getTime();
  const legoJsonName = `lego-${epoch}.json`;

  try {
    const response = await axios.get(
      `https://hornbeam.justmaple.app/data/${legoJsonName}`,
    );
    return response.data;
  } catch (e) {
    const { body } = await downloadLego(legoJsonName);
    return body;
  }
}

export const LegoThemes = [
  { id: 1, name: "Technic", parent_id: null },
  { id: 3, name: "Competition", parent_id: 1 },
  { id: 4, name: "Expert Builder", parent_id: 1 },
  { id: 16, name: "RoboRiders", parent_id: 1 },
  { id: 17, name: "Speed Slammers", parent_id: 1 },
  { id: 18, name: "Star Wars", parent_id: 1 },
  { id: 19, name: "Supplemental", parent_id: 1 },
  { id: 20, name: "Throwbot Slizer", parent_id: 1 },
  { id: 21, name: "Universal Building Set", parent_id: 1 },
  { id: 22, name: "Creator", parent_id: null },
  { id: 34, name: "Make & Create", parent_id: null },
  { id: 35, name: "Bricks & More", parent_id: 34 },
  { id: 50, name: "Town", parent_id: null },
  { id: 51, name: "Arctic", parent_id: 50 },
  { id: 52, name: "City", parent_id: null },
  { id: 53, name: "Airport", parent_id: 52 },
  { id: 54, name: "Cargo", parent_id: 52 },
  { id: 55, name: "Coast Guard", parent_id: 52 },
  { id: 56, name: "Construction", parent_id: 52 },
  { id: 57, name: "Farm", parent_id: 52 },
  { id: 58, name: "Fire", parent_id: 52 },
  { id: 59, name: "Harbor", parent_id: 52 },
  { id: 60, name: "Hospital", parent_id: 52 },
  { id: 61, name: "Police", parent_id: 52 },
  { id: 63, name: "Traffic", parent_id: 52 },
  { id: 64, name: "Off-Road", parent_id: 52 },
  { id: 65, name: "Arctic", parent_id: 52 },
  { id: 66, name: "Trains", parent_id: 52 },
  { id: 67, name: "Classic Town", parent_id: 50 },
  { id: 86, name: "Divers", parent_id: 50 },
  { id: 87, name: "Extreme Team", parent_id: 50 },
  { id: 88, name: "Launch Command", parent_id: 50 },
  { id: 89, name: "Outback", parent_id: 50 },
  { id: 90, name: "Paradisa", parent_id: 50 },
  { id: 91, name: "Race", parent_id: 50 },
  { id: 92, name: "Res-Q", parent_id: 50 },
  { id: 93, name: "Space Port", parent_id: 50 },
  { id: 94, name: "Town Jr.", parent_id: 50 },
  { id: 104, name: "Town Plan", parent_id: 50 },
  { id: 105, name: "World City", parent_id: 50 },
  { id: 106, name: "City Center", parent_id: 50 },
  { id: 112, name: "Racers", parent_id: null },
  { id: 114, name: "Ferrari", parent_id: 112 },
  { id: 118, name: "Promotional", parent_id: 112 },
  { id: 122, name: "RC", parent_id: 112 },
  { id: 123, name: "World Racers", parent_id: 112 },
  { id: 126, name: "Space", parent_id: null },
  { id: 127, name: "Alien Conquest", parent_id: 126 },
  { id: 128, name: "Blacktron I", parent_id: 126 },
  { id: 129, name: "Blacktron II", parent_id: 126 },
  { id: 130, name: "Classic Space", parent_id: 126 },
  { id: 131, name: "Exploriens", parent_id: 126 },
  { id: 132, name: "Futuron", parent_id: 126 },
  { id: 133, name: "Ice Planet 2002", parent_id: 126 },
  { id: 134, name: "Insectoids", parent_id: 126 },
  { id: 135, name: "Life On Mars", parent_id: 126 },
  { id: 136, name: "M:Tron", parent_id: 126 },
  { id: 137, name: "Mars Mission", parent_id: 126 },
  { id: 138, name: "RoboForce", parent_id: 126 },
  { id: 139, name: "Space Police I", parent_id: 126 },
  { id: 140, name: "Space Police II", parent_id: 126 },
  { id: 141, name: "Space Police III", parent_id: 126 },
  { id: 142, name: "Spyrius", parent_id: 126 },
  { id: 143, name: "Supplemental", parent_id: 126 },
  { id: 144, name: "UFO", parent_id: 126 },
  { id: 145, name: "Unitron", parent_id: 126 },
  { id: 146, name: "Galaxy Squad", parent_id: 126 },
  { id: 147, name: "Pirates", parent_id: null },
  { id: 148, name: "Pirates I", parent_id: 147 },
  { id: 153, name: "Pirates II", parent_id: 147 },
  { id: 154, name: "Pirates III", parent_id: 147 },
  { id: 155, name: "Modular Buildings", parent_id: null },
  { id: 156, name: "Mini", parent_id: 155 },
  { id: 157, name: "Bricktober", parent_id: 598 },
  { id: 158, name: "Star Wars", parent_id: null },
  { id: 171, name: "Ultimate Collector Series", parent_id: 158 },
  { id: 186, name: "Castle", parent_id: null },
  { id: 187, name: "Black Falcons", parent_id: 186 },
  { id: 188, name: "Black Knights", parent_id: 186 },
  { id: 189, name: "Classic Castle", parent_id: 186 },
  { id: 190, name: "Dragon Knights", parent_id: 186 },
  { id: 191, name: "Dark Forest", parent_id: 186 },
  { id: 193, name: "Fantasy Era", parent_id: 186 },
  { id: 194, name: "Forestmen", parent_id: 186 },
  { id: 195, name: "Fright Knights", parent_id: 186 },
  { id: 196, name: "Kingdoms", parent_id: 186 },
  { id: 197, name: "Knights Kingdom I", parent_id: 186 },
  { id: 198, name: "Knights Kingdom II", parent_id: 186 },
  { id: 199, name: "Lion Knights", parent_id: 186 },
  { id: 201, name: "Royal Knights", parent_id: 186 },
  { id: 203, name: "Wolfpack", parent_id: 186 },
  { id: 204, name: "Designer Sets", parent_id: 22 },
  { id: 206, name: "Seasonal", parent_id: null },
  { id: 207, name: "Advent", parent_id: 206 },
  { id: 208, name: "City", parent_id: 207 },
  { id: 209, name: "Star Wars", parent_id: 207 },
  { id: 210, name: "Belville", parent_id: 207 },
  { id: 211, name: "Castle", parent_id: 207 },
  { id: 212, name: "Classic Basic", parent_id: 207 },
  { id: 213, name: "Clikits", parent_id: 207 },
  { id: 214, name: "Creator", parent_id: 207 },
  { id: 215, name: "Pirates", parent_id: 207 },
  { id: 216, name: "Friends", parent_id: 207 },
  { id: 227, name: "Christmas", parent_id: 206 },
  { id: 228, name: "Creator", parent_id: 227 },
  { id: 229, name: "Easter", parent_id: 206 },
  { id: 230, name: "Halloween", parent_id: 206 },
  { id: 231, name: "Thanksgiving", parent_id: 206 },
  { id: 232, name: "Valentine", parent_id: 206 },
  { id: 233, name: "Train", parent_id: null },
  { id: 234, name: "12V", parent_id: 233 },
  { id: 235, name: "4.5V", parent_id: 233 },
  { id: 236, name: "9V", parent_id: 233 },
  { id: 240, name: "RC Train", parent_id: 233 },
  { id: 241, name: "Supplemental", parent_id: 233 },
  { id: 246, name: "Harry Potter", parent_id: null },
  { id: 252, name: "Architecture", parent_id: null },
  { id: 253, name: "Skylines", parent_id: 252 },
  { id: 254, name: "Bulk Bricks", parent_id: null },
  { id: 258, name: "Mindstorms", parent_id: null },
  { id: 259, name: "NXT", parent_id: 258 },
  { id: 260, name: "RCX", parent_id: 258 },
  { id: 261, name: "Star Wars", parent_id: 258 },
  { id: 262, name: "EV3", parent_id: 258 },
  { id: 263, name: "Pirates of the Caribbean", parent_id: 608 },
  { id: 264, name: "Indiana Jones", parent_id: null },
  { id: 269, name: "Cars", parent_id: null },
  { id: 270, name: "Ben 10", parent_id: null },
  { id: 271, name: "Prince of Persia", parent_id: 608 },
  { id: 272, name: "SpongeBob SquarePants", parent_id: null },
  { id: 273, name: "Studios", parent_id: null },
  { id: 274, name: "Jurassic Park III", parent_id: 273 },
  { id: 275, name: "Toy Story", parent_id: null },
  { id: 276, name: "Sculptures", parent_id: null },
  { id: 277, name: "Mosaic", parent_id: 276 },
  { id: 278, name: "Model Team", parent_id: null },
  { id: 279, name: "4 Juniors", parent_id: null },
  { id: 280, name: "Jack Stone", parent_id: 279 },
  { id: 287, name: "Spider-Man", parent_id: 279 },
  { id: 296, name: "Adventurers", parent_id: null },
  { id: 297, name: "Desert", parent_id: 296 },
  { id: 298, name: "Dino Island", parent_id: 296 },
  { id: 299, name: "Jungle", parent_id: 296 },
  { id: 300, name: "Orient Expedition", parent_id: 296 },
  { id: 301, name: "Other", parent_id: null },
  { id: 302, name: "Agents", parent_id: null },
  { id: 303, name: "Ultra Agents", parent_id: 302 },
  { id: 304, name: "Alpha Team", parent_id: null },
  { id: 305, name: "Mission Deep Sea", parent_id: 304 },
  { id: 306, name: "Mission Deep Freeze", parent_id: 304 },
  { id: 307, name: "Aquazone", parent_id: null },
  { id: 308, name: "Aquanauts", parent_id: 307 },
  { id: 309, name: "Aquaraiders I", parent_id: 307 },
  { id: 310, name: "Aquaraiders II", parent_id: 307 },
  { id: 311, name: "Aquasharks", parent_id: 307 },
  { id: 312, name: "Hydronauts", parent_id: 307 },
  { id: 313, name: "Stingrays", parent_id: 307 },
  { id: 315, name: "Atlantis", parent_id: null },
  { id: 317, name: "Avatar: The Last Airbender", parent_id: null },
  { id: 318, name: "Belville", parent_id: null },
  { id: 324, name: "Bionicle", parent_id: null },
  { id: 341, name: "Playsets", parent_id: 324 },
  { id: 360, name: "Protectors", parent_id: 324 },
  { id: 363, name: "Boat", parent_id: null },
  { id: 364, name: "Building Set with People", parent_id: null },
  { id: 365, name: "System", parent_id: null },
  { id: 368, name: "HO 1:87 Vehicles", parent_id: 365 },
  { id: 369, name: "Jumbo Bricks", parent_id: 365 },
  { id: 371, name: "Supplemental", parent_id: 365 },
  { id: 372, name: "Town Plan", parent_id: 365 },
  { id: 385, name: "Dino Attack / Dino 2010", parent_id: null },
  { id: 386, name: "Dinosaurs", parent_id: null },
  { id: 387, name: "Discovery", parent_id: null },
  { id: 388, name: "Mickey Mouse", parent_id: 608 },
  { id: 389, name: "Exo-Force", parent_id: null },
  { id: 390, name: "Fabuland", parent_id: null },
  { id: 397, name: "Factory", parent_id: null },
  { id: 398, name: "FIRST LEGO League", parent_id: null },
  { id: 399, name: "Freestyle", parent_id: null },
  { id: 400, name: "Hero Factory", parent_id: null },
  { id: 401, name: "Heroes", parent_id: 400 },
  { id: 403, name: "Villains", parent_id: 400 },
  { id: 404, name: "Hobby Sets", parent_id: null },
  { id: 405, name: "Homemaker", parent_id: null },
  { id: 406, name: "Inventor", parent_id: 22 },
  { id: 407, name: "Island Xtreme Stunts", parent_id: null },
  { id: 408, name: "LEGO Brand Store", parent_id: null },
  { id: 409, name: "Monthly Mini Model Build", parent_id: 408 },
  { id: 410, name: "Pick A Model", parent_id: 408 },
  { id: 411, name: "Legoland", parent_id: null },
  { id: 412, name: "Airport", parent_id: 411 },
  { id: 413, name: "Building", parent_id: 411 },
  { id: 414, name: "Castle", parent_id: 411 },
  { id: 415, name: "Coast Guard", parent_id: 411 },
  { id: 416, name: "Construction", parent_id: 411 },
  { id: 417, name: "Fire", parent_id: 411 },
  { id: 418, name: "Gas Station", parent_id: 411 },
  { id: 419, name: "Harbor", parent_id: 411 },
  { id: 420, name: "Hospital", parent_id: 411 },
  { id: 421, name: "Police", parent_id: 411 },
  { id: 422, name: "Space", parent_id: 411 },
  { id: 423, name: "Vehicle", parent_id: 411 },
  { id: 424, name: "Western", parent_id: 411 },
  { id: 425, name: "Legoland Parks", parent_id: null },
  { id: 432, name: "Master Builder Academy", parent_id: null },
  { id: 433, name: "Minitalia", parent_id: null },
  { id: 434, name: "Ninja", parent_id: null },
  { id: 435, name: "Ninjago", parent_id: null },
  { id: 437, name: "Pharaoh's Quest", parent_id: null },
  { id: 438, name: "Power Functions", parent_id: null },
  { id: 439, name: "Power Miners", parent_id: null },
  { id: 440, name: "Primo", parent_id: null },
  { id: 441, name: "Quatro", parent_id: null },
  { id: 442, name: "Rock Raiders", parent_id: null },
  { id: 443, name: "Service Packs", parent_id: null },
  { id: 453, name: "Technic", parent_id: 443 },
  { id: 456, name: "Train", parent_id: 443 },
  { id: 458, name: "Sports", parent_id: null },
  { id: 459, name: "Basketball", parent_id: 458 },
  { id: 460, name: "Gravity Games", parent_id: 458 },
  { id: 461, name: "Hockey", parent_id: 458 },
  { id: 462, name: "Soccer", parent_id: 458 },
  { id: 463, name: "Spybotics", parent_id: null },
  { id: 464, name: "Time Cruisers", parent_id: null },
  { id: 465, name: "Universal Building Set", parent_id: null },
  { id: 467, name: "Basic", parent_id: 465 },
  { id: 470, name: "Classic Basic", parent_id: 465 },
  { id: 471, name: "Ferries", parent_id: 598 },
  { id: 472, name: "Gears", parent_id: 465 },
  { id: 473, name: "Supplemental", parent_id: 465 },
  { id: 474, name: "Vikings", parent_id: null },
  { id: 475, name: "Western", parent_id: null },
  { id: 478, name: "X-Pod", parent_id: 22 },
  { id: 480, name: "Znap", parent_id: null },
  { id: 481, name: "Dino", parent_id: null },
  { id: 494, name: "Friends", parent_id: null },
  { id: 497, name: "Books", parent_id: null },
  { id: 498, name: "Technic", parent_id: 497 },
  { id: 500, name: "Clikits", parent_id: null },
  { id: 501, name: "Gear", parent_id: null },
  { id: 502, name: "Games", parent_id: null },
  { id: 503, name: "Key Chain", parent_id: 501 },
  { id: 504, name: "Duplo", parent_id: null },
  { id: 505, name: "Basic Set", parent_id: 504 },
  { id: 506, name: "Cars", parent_id: 754 },
  { id: 507, name: "Educational and Dacta", parent_id: null },
  { id: 509, name: "SPIKE", parent_id: 507 },
  { id: 510, name: "Serious Play", parent_id: 507 },
  { id: 511, name: "Building Set with People", parent_id: 507 },
  { id: 516, name: "Duplo and Explore", parent_id: 507 },
  { id: 517, name: "Learning", parent_id: 507 },
  { id: 518, name: "Mindstorms", parent_id: 507 },
  { id: 519, name: "NXT", parent_id: 518 },
  { id: 520, name: "RCX", parent_id: 518 },
  { id: 521, name: "WeDo", parent_id: 518 },
  { id: 523, name: "Samsonite", parent_id: 507 },
  { id: 524, name: "Service Packs", parent_id: 507 },
  { id: 525, name: "Technic", parent_id: 524 },
  { id: 526, name: "Soft Bricks", parent_id: 507 },
  { id: 528, name: "Supplemental", parent_id: 507 },
  { id: 529, name: "Technic", parent_id: 507 },
  { id: 530, name: "Control Lab", parent_id: 529 },
  { id: 531, name: "eLAB", parent_id: 529 },
  { id: 533, name: "Town", parent_id: 507 },
  { id: 534, name: "Universal Building Set", parent_id: 507 },
  { id: 535, name: "Collectible Minifigures", parent_id: null },
  { id: 536, name: "Series 1 Minifigures", parent_id: 535 },
  { id: 537, name: "Series 2 Minifigures", parent_id: 535 },
  { id: 538, name: "Series 3 Minifigures", parent_id: 535 },
  { id: 539, name: "Series 4 Minifigures", parent_id: 535 },
  { id: 540, name: "Series 5 Minifigures", parent_id: 535 },
  { id: 541, name: "Series 6 Minifigures", parent_id: 535 },
  { id: 542, name: "Series 7 Minifigures", parent_id: 535 },
  { id: 543, name: "Series 8 Minifigures", parent_id: 535 },
  { id: 544, name: "Series 9 Minifigures", parent_id: 535 },
  { id: 545, name: "Series 10 Minifigures", parent_id: 535 },
  { id: 546, name: "Team GB", parent_id: 535 },
  { id: 547, name: "Series 11 Minifigures", parent_id: 535 },
  { id: 548, name: "Series 12 Minifigures", parent_id: 535 },
  { id: 549, name: "The LEGO Movie", parent_id: 535 },
  { id: 550, name: "The Simpsons Series 1", parent_id: 535 },
  { id: 551, name: "Series 13 Minifigures", parent_id: 535 },
  { id: 552, name: "Series 14 Minifigures", parent_id: 535 },
  { id: 553, name: "The Simpsons Series 2", parent_id: 535 },
  { id: 554, name: "Series 15 Minifigures", parent_id: 535 },
  { id: 555, name: "Disney Series 1", parent_id: 535 },
  { id: 556, name: "Series 16 Minifigures", parent_id: 535 },
  { id: 557, name: "DFB Minifigures", parent_id: 535 },
  { id: 558, name: "Monster Fighters", parent_id: null },
  { id: 559, name: "Value Packs", parent_id: null },
  { id: 560, name: "Universe", parent_id: null },
  { id: 561, name: "The Hobbit and Lord of the Rings", parent_id: null },
  { id: 562, name: "The Hobbit", parent_id: 561 },
  { id: 566, name: "The Lord of the Rings", parent_id: 561 },
  { id: 570, name: "Teenage Mutant Ninja Turtles", parent_id: null },
  { id: 571, name: "Legends of Chima", parent_id: null },
  { id: 572, name: "Speedorz", parent_id: 571 },
  { id: 573, name: "Constraction", parent_id: 571 },
  { id: 575, name: "The Lone Ranger", parent_id: null },
  { id: 576, name: "LEGO Ideas", parent_id: null },
  { id: 577, name: "Minecraft", parent_id: null },
  { id: 578, name: "The LEGO Movie", parent_id: null },
  { id: 579, name: "Disney Princess", parent_id: 608 },
  { id: 580, name: "Mixels", parent_id: null },
  { id: 590, name: "Fusion", parent_id: null },
  { id: 591, name: "Juniors", parent_id: null },
  { id: 592, name: "DC Comics Super Heroes", parent_id: 591 },
  { id: 593, name: "Disney Princess", parent_id: 591 },
  { id: 595, name: "Friends", parent_id: 591 },
  { id: 596, name: "Marvel Super Heroes", parent_id: 591 },
  { id: 597, name: "Ninjago", parent_id: 591 },
  { id: 598, name: "Promotional", parent_id: null },
  { id: 599, name: "LEGO Exclusive", parent_id: null },
  { id: 600, name: "Elves", parent_id: null },
  { id: 601, name: "Speed Champions", parent_id: null },
  { id: 602, name: "Jurassic World", parent_id: null },
  { id: 603, name: "Scooby-Doo", parent_id: null },
  { id: 604, name: "Dimensions", parent_id: null },
  { id: 605, name: "Nexo Knights", parent_id: null },
  { id: 606, name: "Angry Birds", parent_id: null },
  { id: 607, name: "Ghostbusters", parent_id: null },
  { id: 608, name: "Disney", parent_id: null },
  { id: 609, name: "The LEGO Batman Movie Series 1", parent_id: 535 },
  { id: 610, name: "Brickheadz", parent_id: null },
  { id: 611, name: "Series 17 Minifigures", parent_id: 535 },
  { id: 614, name: "Jungle", parent_id: 52 },
  { id: 615, name: "Cars", parent_id: 591 },
  { id: 616, name: "The LEGO Ninjago Movie", parent_id: 435 },
  { id: 617, name: "DC Super Hero Girls", parent_id: null },
  { id: 618, name: "The LEGO Ninjago Movie", parent_id: 535 },
  { id: 619, name: "Cities of Wonders", parent_id: 408 },
  { id: 620, name: "Jurassic World: Fallen Kingdom", parent_id: 591 },
  { id: 621, name: "Classic", parent_id: null },
  { id: 622, name: "Series 18 Minifigures", parent_id: 535 },
  { id: 625, name: "Unikitty!", parent_id: null },
  { id: 626, name: "Bob the Builder", parent_id: 504 },
  { id: 627, name: "Planes", parent_id: 754 },
  { id: 628, name: "Dora the Explorer", parent_id: 504 },
  { id: 629, name: "Miles From Tomorrowland", parent_id: 754 },
  { id: 630, name: "Marvel", parent_id: 504 },
  { id: 631, name: "Thomas & Friends", parent_id: 504 },
  { id: 632, name: "Town", parent_id: 504 },
  { id: 633, name: "Toy Story", parent_id: 754 },
  { id: 634, name: "Trains", parent_id: 504 },
  { id: 635, name: "Winnie the Pooh", parent_id: 754 },
  { id: 636, name: "My Town", parent_id: 632 },
  { id: 638, name: "Jake and the Never Land Pirates", parent_id: 754 },
  { id: 639, name: "Sofia the First", parent_id: 504 },
  { id: 640, name: "Disney Princess", parent_id: 754 },
  { id: 641, name: "Mickey & Friends", parent_id: 754 },
  { id: 646, name: "Xtra", parent_id: null },
  { id: 647, name: "Castle", parent_id: 504 },
  { id: 648, name: "Doc McStuffins", parent_id: 754 },
  { id: 650, name: "Legoville", parent_id: 632 },
  { id: 651, name: "Pirates", parent_id: 504 },
  { id: 652, name: "Playhouse", parent_id: 504 },
  { id: 653, name: "DC Comics", parent_id: 504 },
  { id: 654, name: "The Powerpuff Girls", parent_id: null },
  { id: 655, name: "Powered Up", parent_id: 438 },
  {
    id: 656,
    name: "Harry Potter and Fantastic Beasts Series 1",
    parent_id: 535,
  },
  { id: 657, name: "Action Wheelers", parent_id: 504 },
  { id: 658, name: "Dino", parent_id: 504 },
  { id: 659, name: "Dolls", parent_id: 504 },
  { id: 660, name: "Little Forest Friends", parent_id: 504 },
  { id: 661, name: "Little Robots", parent_id: 504 },
  { id: 662, name: "Princess Castle", parent_id: 504 },
  { id: 663, name: "Rattles", parent_id: 504 },
  { id: 664, name: "Toolo", parent_id: 504 },
  { id: 665, name: "Western", parent_id: 504 },
  { id: 666, name: "Zooters", parent_id: 504 },
  { id: 667, name: "Fantastic Beasts", parent_id: 246 },
  { id: 668, name: "Scala", parent_id: null },
  { id: 669, name: "Overwatch", parent_id: null },
  { id: 670, name: "The LEGO Movie II", parent_id: 578 },
  { id: 671, name: "Forma", parent_id: null },
  { id: 672, name: "Creator 3-in-1", parent_id: 22 },
  { id: 673, name: "Creator Expert", parent_id: 22 },
  { id: 674, name: "Early Creator", parent_id: 22 },
  { id: 675, name: "The LEGO Movie II", parent_id: 535 },
  { id: 676, name: "Hidden Side", parent_id: null },
  { id: 677, name: "Disney Series 2", parent_id: 535 },
  { id: 679, name: "Mars Exploration", parent_id: 52 },
  { id: 680, name: "Stranger Things", parent_id: null },
  { id: 681, name: "Series 19 Minifigures", parent_id: 535 },
  { id: 682, name: "Trolls: World Tour", parent_id: null },
  { id: 683, name: "LEGO Originals", parent_id: null },
  { id: 684, name: "DC Super Heroes", parent_id: 535 },
  { id: 685, name: "Galidor", parent_id: null },
  { id: 686, name: "Chinese Traditional Festivals", parent_id: null },
  { id: 687, name: "Frozen", parent_id: 608 },
  { id: 688, name: "DOTS", parent_id: null },
  { id: 689, name: "Minions", parent_id: null },
  { id: 690, name: "Super Mario", parent_id: null },
  {
    id: 691,
    name: "Harry Potter and Fantastic Beasts Series 2",
    parent_id: 535,
  },
  { id: 692, name: "Series 20 Minifigures", parent_id: 535 },
  { id: 693, name: "Monkie Kid", parent_id: null },
  { id: 694, name: "Brick Sketches", parent_id: null },
  { id: 695, name: "Super Heroes DC", parent_id: null },
  { id: 696, name: "Super Heroes Marvel", parent_id: null },
  { id: 697, name: "Batman", parent_id: 695 },
  { id: 698, name: "UCS", parent_id: 697 },
  { id: 700, name: "Justice League", parent_id: 695 },
  { id: 701, name: "Superman", parent_id: 695 },
  { id: 702, name: "Avengers", parent_id: 696 },
  { id: 704, name: "Guardians of the Galaxy", parent_id: 696 },
  { id: 705, name: "Iron Man", parent_id: 696 },
  { id: 706, name: "Spider-Man", parent_id: 696 },
  { id: 707, name: "X-Men", parent_id: 696 },
  { id: 708, name: "The LEGO Batman Movie", parent_id: 697 },
  { id: 709, name: "LEGO Art", parent_id: null },
  { id: 710, name: "Harry Potter", parent_id: 207 },
  { id: 711, name: "The LEGO Batman Movie Series 2", parent_id: 535 },
  { id: 712, name: "Series 21 Minifigures", parent_id: 535 },
  { id: 713, name: "VIDIYO", parent_id: null },
  { id: 714, name: "Looney Tunes", parent_id: 535 },
  { id: 715, name: "Marvel Series 1", parent_id: 535 },
  { id: 716, name: "Modulex", parent_id: null },
  { id: 717, name: "Speed Racer", parent_id: null },
  { id: 718, name: "Series 22 Minifigures", parent_id: 535 },
  { id: 719, name: "BrickLink Designer Program", parent_id: null },
  { id: 720, name: "The Muppets", parent_id: 535 },
  { id: 721, name: "Icons", parent_id: null },
  { id: 722, name: "Jurassic World", parent_id: 504 },
  { id: 724, name: "Avatar", parent_id: null },
  { id: 725, name: "Series 23 Minifigures", parent_id: 535 },
  { id: 728, name: "McDonalds", parent_id: 598 },
  { id: 729, name: "Airlines", parent_id: 598 },
  { id: 730, name: "Audio and Visual Media", parent_id: 501 },
  { id: 731, name: "Bag and Luggage Tags", parent_id: 501 },
  { id: 732, name: "Clocks and Watches", parent_id: 501 },
  { id: 733, name: "Houseware", parent_id: 501 },
  { id: 734, name: "Magnets", parent_id: 501 },
  { id: 735, name: "Plush Toys", parent_id: 501 },
  { id: 736, name: "Posters and Art Prints", parent_id: 501 },
  { id: 737, name: "Role Play Toys and Costumes", parent_id: 501 },
  { id: 738, name: "Seasonal", parent_id: 501 },
  { id: 739, name: "Stationery and Office Supplies", parent_id: 501 },
  { id: 740, name: "Storage", parent_id: 501 },
  { id: 741, name: "Tabletop Games and Puzzles", parent_id: 501 },
  { id: 742, name: "Video Games and Accessories", parent_id: 501 },
  { id: 743, name: "Series 24 Minifigures", parent_id: 535 },
  { id: 744, name: "Stuntz", parent_id: 52 },
  { id: 745, name: "Disney 100", parent_id: 535 },
  { id: 746, name: "Database Sets", parent_id: 301 },
  { id: 747, name: "Sonic The Hedgehog", parent_id: null },
  { id: 748, name: "Gabby's Dollhouse", parent_id: null },
  { id: 749, name: "Dreamzzz", parent_id: null },
  { id: 750, name: "Marvel Series 2", parent_id: 535 },
  { id: 751, name: "Marvel", parent_id: 207 },
  { id: 752, name: "Animal Crossing", parent_id: null },
  { id: 753, name: "Series 25 Minifigures", parent_id: 535 },
  { id: 754, name: "Disney", parent_id: 504 },
  { id: 755, name: "Spidey and His Amazing Friends", parent_id: 706 },
  { id: 756, name: "Samsonite", parent_id: 365 },
  { id: 757, name: "Ideas Books", parent_id: 497 },
  { id: 758, name: "Non-fiction Books", parent_id: 497 },
  { id: 759, name: "Story Books", parent_id: 497 },
  { id: 760, name: "Activity Books", parent_id: 497 },
  { id: 761, name: "Activity Books with LEGO Parts", parent_id: 497 },
  { id: 762, name: "Series 26 Minifigures", parent_id: 535 },
  { id: 763, name: "Despicable Me 4", parent_id: null },
  { id: 764, name: "The Legend of Zelda", parent_id: null },
  { id: 765, name: "Wicked", parent_id: null },
  { id: 766, name: "Fortnite", parent_id: null },
  { id: 767, name: "Dungeons & Dragons", parent_id: 535 },
];
